/* sim/parser_add.hh
Copyright (C) 2016 Chun-Chung Chen <cjj@u.washington.edu>

This file is part of cst.

cst is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with cst.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef PARSER_ADD_HH
#define PARSER_ADD_HH
#include <arg.hh>
class ParserAdd
{
public:
	virtual ~ParserAdd() {}
	// add options to parser
	virtual void addto_parser(arg::Parser & /*parser*/) {}
	// Commit parsed value to the actual parameters.
	//   For buffered parser options, like that generated by prm::Argu,
	//   this should be called after parsing.
	virtual bool alter() {return false;}
};
#endif
